//! Πprm - proof that the ring-Pedersen parameter s lies in the subgroup
//! generated by t modulo N̂ (i.e., s = t^λ for known λ). Non-interactive,
//! M parallel repetitions with 1-bit challenges (soundness 2^-M).
//!
//! Ported from cggmp24/src/zk/ring_pedersen_parameters.rs.

const std = @import("std");
const common = @import("common.zig");
const Transcript = common.Transcript;

pub fn Prm(comptime P: type, comptime M: usize) type {
    const Aux = common.Aux(P);
    return struct {
        pub const Proof = struct {
            commitment: [M]P.Fn.Bytes,
            zs: [M]P.Fn.Bytes,
        };

        fn challengeBits(tr: Transcript, aux: Aux, commitment: *const [M]P.Fn.Bytes) [M]bool {
            var t = tr.fork("zig-mpc/zk/prm/v1");
            aux.appendToTranscript(&t);
            for (commitment) |a| t.appendBytes("commitment", &a);
            var rng = t.challengeRng();
            var bytes: [M]u8 = undefined;
            rng.fill(&bytes);
            var es: [M]bool = undefined;
            for (&es, bytes) |*e, b| e.* = (b & 1) == 1;
            return es;
        }

        /// `phi` = φ(N̂), `lambda` such that s = t^λ.
        pub fn prove(tr: Transcript, rng: std.Random, aux: Aux, phi: P.Fn.Bytes, lambda: P.Fn.Bytes) Proof {
            var as: [M]P.Fn.Bytes = undefined;
            var commitment: [M]P.Fn.Bytes = undefined;
            for (&as, &commitment) |*a, *com| {
                a.* = P.Fn.sampleBelow(rng, phi);
                com.* = aux.powBytes(aux.t, a);
            }
            const es = challengeBits(tr, aux, &commitment);
            var zs: [M]P.Fn.Bytes = undefined;
            for (&zs, as, es) |*z, a, e| {
                if (e) {
                    // z = a + λ mod φ
                    var sum = P.Fn.widen(P.FInt, a);
                    _ = P.FInt.addInPlace(&sum, P.Fn.widen(P.FInt, lambda));
                    const red = P.FInt.divRem(sum, P.Fn.widen(P.FInt, phi)) catch unreachable;
                    z.* = P.FInt.narrow(P.Fn, red.r) catch unreachable;
                } else {
                    z.* = a;
                }
            }
            return .{ .commitment = commitment, .zs = zs };
        }

        pub fn verify(tr: Transcript, aux: Aux, proof: Proof) !void {
            if (!aux.isInMultGroup(aux.s) or !aux.isInMultGroup(aux.t)) return error.InvalidProof;
            for (proof.commitment, proof.zs) |a, z| {
                if (!aux.isInMultGroup(a)) return error.InvalidProof;
                if (P.Fn.cmp(z, aux.n_hat) != .lt) return error.InvalidProof;
            }
            const es = challengeBits(tr, aux, &proof.commitment);
            for (proof.zs, proof.commitment, es) |z, a, e| {
                const lhs = aux.powBytes(aux.t, &z);
                const rhs = if (e) aux.mulMod(aux.s, a) else a;
                if (!std.mem.eql(u8, &lhs, &rhs)) return error.InvalidProof;
            }
        }
    };
}

test "prm passing and failing" {
    const P = common.TestParams;
    const Z = Prm(P, 16);
    var prng = std.Random.DefaultPrng.init(101);
    const rng = prng.random();

    var gen = try common.Aux(P).generate(rng, false);
    defer gen.secret.zeroize();

    var tr = Transcript.init("zig-mpc/test/prm");
    tr.appendBytes("session", "abc");

    const proof = Z.prove(tr, rng, gen.aux, gen.secret.phi, gen.secret.lambda);
    try Z.verify(tr, gen.aux, proof);

    // different transcript -> rejected
    var tr2 = Transcript.init("zig-mpc/test/prm");
    tr2.appendBytes("session", "xyz");
    try std.testing.expectError(error.InvalidProof, Z.verify(tr2, gen.aux, proof));

    // wrong s (shifted by 1) -> rejected
    var bad_aux = gen.aux;
    var s_plus = bad_aux.s;
    _ = P.Fn.addInPlace(&s_plus, P.Fn.fromU64(1));
    bad_aux.s = s_plus;
    const bad_proof = Z.prove(tr, rng, bad_aux, gen.secret.phi, gen.secret.lambda);
    try std.testing.expectError(error.InvalidProof, Z.verify(tr, bad_aux, bad_proof));

    // tampered z -> rejected
    var tampered = proof;
    _ = P.Fn.addInPlace(&tampered.zs[3], P.Fn.fromU64(1));
    try std.testing.expectError(error.InvalidProof, Z.verify(tr, gen.aux, tampered));
}
